server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    user:
      name: user
      password: password

jwt:
  secret: miClaveSecretaSuperSeguraParaJWT2024CarWashProyecto
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/